---
title: "DAGs"
author: "Joanna"
format: html
editor: visual
---

```{r Setup}
library(tidyverse)
library(dagitty)
library(ggdag)
```

# DAGs

quelques essais de création de DAGs.

```{r dag exemple}
#| echo: false
#| fig-width: 3
#| fig-height: 3
dag <- dagify(
  R ~ M,
  M ~ P,
  R ~ P,
  coords = list(
    x = c(M = 0, R = 2, P = 1),
    y = c(M = 0, R = 0, P = 1)
  )
)

ggdag(dag) + theme_dag()
```

```{r DAG mammites}
#| echo: false
#| fig-width: 3
#| fig-height: 3
dag_mammites <- dagify(
  PL ~ M,
  D ~ M,
  AI ~ M,
  F ~ AI,
  R ~ F,
  R ~ PL,
  R ~ D,
  coords = list(
    x = c(M = 0, R = 3, PL = 1, D = 1, AI = 1, F = 2),
    y = c(M = 1, R = 1, PL = 1, D = 2, AI = 0, F = 0)
  )
)

ggdag(dag_mammites) + theme_dag()
```

```{r DAG mam-mise à la reproduction}
#| echo: false
#| fig-width: 3
#| fig-height: 3
dag_mam_repro <- dagify(
  PL ~ ~ M,
  AI ~ M + PL + P + T + G,
  F ~ AI,
  R ~ F,
  coords = list(
    x = c(M = 0, AI = 1, P = 0.5, T = 1, PL = 1, G = 1.5, F = 2, R = 3),
    y = c(M = 2, R = 2, F = 2, AI = 2, PL = 3, T = 0, P = 0.5, G = 0.5),
    exposure = "M",
    outcome = "AI"
  )
) 

ggdag(dag_mam_repro) + theme_dag()


# Définir le graphe causal avec les variables latentes
dag_mam_repro <- dagify(
  PL ~ M,
  AI ~ M + PL + P + T + G,
  F ~ AI,
  R ~ F,
  coords = list(
    x = c(M = 0, AI = 1, P = 0.5, T = 1, PL = 1, G = 1.5, F = 2, R = 3),
    y = c(M = 2, R = 2, F = 2, AI = 2, PL = 3, T = 0, P = 0.5, G = 0.5),
    exposure = "M",
    outcome = "AI"
  ),
  latent = c("T", "G")
)

# Visualiser le graphe avec ggdag
ggdag(dag_mam_repro) + theme_dag()
```

```{r}
library(dagitty)

dag <- dagitty(
  A -> B,
  B -> C,
  C -> D,
  Latent("Facteur") -> A,
  Latent("Facteur") -> C
)

# Visualiser le DAG
dag
```

```{r}
# Définir le graphe causal avec les variables latentes
dag_mam_repro <- dagitty::dagitty('
  dag {
    M [exposure]
    AI [outcome]
    T [latent]
    G [latent]
    M -> PL
    M -> AI
    PL -> AI
    P -> AI
    T -> AI
    G -> AI
    AI -> F
    F -> R
  }
')

# Définir les coordonnées pour le DAG
coordinates(dag_mam_repro) <- list(
  x = c(M = 0, AI = 1, P = 0.5, T = 1, PL = 1, G = 1.5, F = 2, R = 3),
  y = c(M = 2, R = 2, F = 2, AI = 2, PL = 3, T = 0, P = 0.5, G = 0.5)
)

# Visualiser le graphe avec ggdag
ggdag_status(dag_mam_repro, use_labels = "name") + 
  geom_dag_text() +
  theme_dag() +
  theme(legend.position = "none")
```

```{r mammite - repro}
# Définir le graphe causal avec les variables latentes
dag_mam_repro <- dagitty::dagitty('
  dag {
    M [exposure]
    I [outcome]
    T [latent]
    G [latent]
    M -> PL
    M -> I
    PL -> I
    P -> I
    T -> I
    G -> I
  }
')

# Définir les coordonnées pour le DAG
coordinates(dag_mam_repro) <- list(
  x = c(M = 0, I = 1, P = 0.5, T = 1, PL = 1, G = 1.5),
  y = c(M = 2, 2, I = 2, PL = 3, T = 0, P = 0.5, G = 0.5)
)

# Convertir en tidy_dagitty pour ggdag
tidy_dag <- tidy_dagitty(dag_mam_repro)

# Ajouter une colonne pour identifier les variables latentes
tidy_dag$data$status <- ifelse(tidy_dag$data$name %in% c("T", "G"), "latent", "observed")

# Créer le ggdag plot avec le nom des variables au centre des nœuds
ggdag(tidy_dag) + 
  geom_dag_node(aes(color = status), size = 10, shape = 21, fill = "black") +
  geom_dag_text(aes(label = name), color = "white", size = 4) +
  theme_dag() +
  scale_color_manual(values = c("latent" = "red", "observed" = "blue"))
```

```{r mammite - IA1}
# Définir le graphe causal avec les variables latentes
dag_mam_repro <- dagitty::dagitty('
  dag {
    M [exposure]
    AI1 [outcome]
    T [latent]
    G [latent]
    M -> PL
    M -> AI1
    PL -> AI1
    P -> AI1
    T -> AI1
    Rc -> AI1
    S -> AI1
    S -> M
  }
')

# Définir les coordonnées pour le DAG
coordinates(dag_mam_repro) <- list(
  x = c(M = 0, AI1 = 1, P = 1.5, T = 2, PL = 0.5, Rc = 1.5, S = 0.5),
  y = c(M = 2, AI1 = 2, PL = 3, T = 1.5, P = 3, Rc = 0.5, S = 0.5)
)

# Convertir en tidy_dagitty pour ggdag
tidy_dag <- tidy_dagitty(dag_mam_repro)

# Ajouter une colonne pour identifier les variables latentes
tidy_dag$data$status <- ifelse(tidy_dag$data$name %in% c("T", "G"), "latent", "observed")

# Créer le ggdag plot avec le nom des variables au centre des nœuds
ggdag(tidy_dag) + 
  geom_dag_node(aes(color = status), size = 10, shape = 21, fill = "black") +
  geom_dag_text(aes(label = name), color = "white", size = 4) +
  theme_dag() +
  scale_color_manual(values = c("latent" = "red", "observed" = "blue"))
```

```{r mammite - nai}
# Définir le graphe causal avec les variables latentes
dag_mam_repro <- dagitty::dagitty('
  dag {
    M [exposure]
    NAI [outcome]
    T [latent]
    G [latent]
    M -> PL
    M -> NAI
    PL -> NAI
    P -> NAI
    T -> NAI
    Rc -> NAI
    S -> NAI
    S -> M
  }
')

# Définir les coordonnées pour le DAG
coordinates(dag_mam_repro) <- list(
  x = c(M = 0, NAI = 1, P = 1.5, T = 2, PL = 0.5, Rc = 1.5, S = 0.5),
  y = c(M = 2, NAI = 2, PL = 3, T = 1.5, P = 3, Rc = 0.5, S = 0.5)
)

# Convertir en tidy_dagitty pour ggdag
tidy_dag <- tidy_dagitty(dag_mam_repro)

# Ajouter une colonne pour identifier les variables latentes
tidy_dag$data$status <- ifelse(tidy_dag$data$name %in% c("T", "G"), "latent", "observed")

# Créer le ggdag plot avec le nom des variables au centre des nœuds
ggdag(tidy_dag) + 
  geom_dag_node(aes(color = status), size = 10, shape = 21, fill = "black") +
  geom_dag_text(aes(label = name), color = "white", size = 4) +
  theme_dag() +
  scale_color_manual(values = c("latent" = "red", "observed" = "blue"))
```

```{r mammite - vêlage}
# Définir le graphe causal avec les variables latentes
dag_mam_repro <- dagitty::dagitty('
  dag {
    M [exposure]
    V [outcome]
    T [latent]
    M -> V
    P -> V
    T -> V
    Rc -> V
    S -> V
    S -> M
  }
')

# Définir les coordonnées pour le DAG
coordinates(dag_mam_repro) <- list(
  x = c(M = 0, V = 1, P = 1.5, T = 2, Rc = 1.5, S = 0.5),
  y = c(M = 2, V = 2, T = 1.5, P = 3, Rc = 0.5, S = 0.5)
)

# Convertir en tidy_dagitty pour ggdag
tidy_dag <- tidy_dagitty(dag_mam_repro)

# Ajouter une colonne pour identifier les variables latentes
tidy_dag$data$status <- ifelse(tidy_dag$data$name %in% c("T", "G"), "latent", "observed")

# Créer le ggdag plot avec le nom des variables au centre des nœuds
ggdag(tidy_dag) + 
  geom_dag_node(aes(color = status), size = 10, shape = 21, fill = "black") +
  geom_dag_text(aes(label = name), color = "white", size = 4) +
  theme_dag() +
  scale_color_manual(values = c("latent" = "red", "observed" = "blue"))
```

```{r}
# Définir le graphe causal avec les variables latentes
dag_mam_repro <- dagitty::dagitty('
  dag {
    M [exposure]
    D [outcome]
    T [latent]
    M -> D
    P -> D
    T -> D
    S -> D
    S -> M
  }
')

# Définir les coordonnées pour le DAG
coordinates(dag_mam_repro) <- list(
  x = c(M = 0, D = 1, P = 1, T = 1.5, S = 0.5),
  y = c(M = 2, D = 2, T = 0.5, P = 3, S = 0.5)
)

# Convertir en tidy_dagitty pour ggdag
tidy_dag <- tidy_dagitty(dag_mam_repro)

# Ajouter une colonne pour identifier les variables latentes
tidy_dag$data$status <- ifelse(tidy_dag$data$name %in% c("T", "G"), "latent", "observed")

# Créer le ggdag plot avec le nom des variables au centre des nœuds
ggdag(tidy_dag) + 
  geom_dag_node(aes(color = status), size = 10, shape = 21, fill = "black") +
  geom_dag_text(aes(label = name), color = "white", size = 4) +
  theme_dag() +
  scale_color_manual(values = c("latent" = "red", "observed" = "blue"))
```

```{r mammite - PL}
# Définir le graphe causal avec les variables latentes
dag_mam_repro <- dagitty::dagitty('
  dag {
    M [exposure]
    PL [outcome]
    T [latent]
    A [latent]
    M -> PL
    PL -> M
    P -> PL
    T -> PL
    S -> PL
    S -> M
    Rc -> PL
    A -> PL
  }
')

# Définir les coordonnées pour le DAG
coordinates(dag_mam_repro) <- list(
  x = c(M = 0, PL = 1, P = 0.5, T = 1.5, S = 0.5, Rc = 1, A = 1.5),
  y = c(M = 2, PL = 2, T = 2.5, P = 2.5, S = 1.5, Rc = 1.5, A = 1.5)
)

# Convertir en tidy_dagitty pour ggdag
tidy_dag <- tidy_dagitty(dag_mam_repro)

# Ajouter une colonne pour identifier les variables latentes
tidy_dag$data$status <- ifelse(tidy_dag$data$name %in% c("T", "A"), "latent", "observed")

# Créer le ggdag plot avec le nom des variables au centre des nœuds
ggdag(tidy_dag) + 
  geom_dag_node(aes(color = status), size = 10, shape = 21, fill = "black") +
  geom_dag_text(aes(label = name), color = "white", size = 4) +
  theme_dag() +
  scale_color_manual(values = c("latent" = "red", "observed" = "blue"))
```
