---
title: "dynamiques des infections intramammaires lors du tarissement"
author: "Joanna"
format: html
editor: visual
---

```{r setup}
#| message: false
library(tidyverse)
library(lme4)
library(marginaleffects)
library(readxl)
library(ggplot2)
library(corrplot)
library(questionr)
library(car)
library(ggeffects)
library(GGally)
library(effects)
library(ggpubr)
library(RColorBrewer)
library(gtsummary)
```

```{r seuil utilisés}
## nombre de jours en dessous duquel on considère qu'on est en début de lactation
## en moyenne avant première IA
early_dim_cutoff <- 90
## SCC cut-off
## seuil de cellules au-delà duquel on considère
## qu'il y a mammite clinique
scc_high_cutoff <- 200
```

# Chargement des données utiles

```{r}
lac <- read.csv2("generated_datasets/idele_lac_final.csv")
mast_pred <- read.csv2("generated_datasets/mast_pred.csv")
parit_pred <- read.csv2("generated_datasets/parity_pred.csv")
milk_pred <- read.csv2("generated_datasets/milk_pred.csv")
race_pred <- read.csv2("generated_datasets/race_pred.csv")
```

```{r}
level_order <- c("primi_healthy", "primi_env", "primi_cont",
                 "dpLow_healthy", "dpLow_env", "dpLow_cont",
                 "dpHigh_healthy", "dpHigh_env", "dpHigh_cont")

```

```{r}
lac <- lac |> 
  mutate(mast_cat1 = relevel(factor(mast_cat1), ref = "primi_healthy"),
         parKat = relevel(factor(parKat), ref = 3),
         race = relevel(factor(race), ref = "PH"))
```

```{r}
lac <- lac |> 
  mutate(calv_date = as.Date(calv_date, "%Y-%m-%d"))
```

```{r}
lac <- lac |> 
  mutate(
    repro = ifelse(!is.na(n_ai), 1, 0))
```

# Probabilité d'un SCC élevé au dernier contrôle avant tarissement

## modélisation

```{r}
scc_high_dp_model <- glmer(infct_end_lac ~ parKat +
                             milk_early_max_scaled_p1 +
                             milk_early_max_scaled_p2 +
                             milk_early_max_scaled_p3 +
                             milk_early_max_scaled_p4 +
                             mast_cat1 +
                             race +
                             (1| herd_id),
                           family = binomial(link = "logit"),
                           data = lac, 
                           subset = n_ctrl_early > 0 & repro == 1 & dp_mis == 0 & !is.na(infct_end_lac),
                           control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))

summary(scc_high_dp_model)
```

```{r}
save(scc_high_dp_model, file = "generated_datasets/scc_high_dp_model.RData")
```


```{r}
t_scc_high <- tbl_regression(scc_high_dp_model, exponentiate = TRUE)
print(t_scc_high)
```

```{r}
saveRDS(t_scc_high, "generated_datasets/t_scc_high.RData")
```


## Prédictions

```{r}
mast_pred <- mast_pred |> 
  mutate(race = as.factor(race),
         parKat = as.factor(parKat),
         mast_cat1 = as.factor(mast_cat1))
```

```{r}
prd <- predictions(model = scc_high_dp_model,
                   newdata = mast_pred,
                   re.form = NA, type = "response")

scc_mam <- ggplot(prd, aes(x = factor(mast_cat1, level = level_order), y = estimate)) +
  geom_point() +
  geom_segment(aes(x = mast_cat1, y=conf.low, xend = mast_cat1, yend = conf.high))+
  xlab("Statut mammite")+
  ylab("probabilité d'un SCC élevé au dernier contrôle avant tarissement")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

scc_mam
```
```{r}
saveRDS(scc_mam, "generated_datasets/scc_mam.RData")
```

```{r}
parit_pred <- parit_pred |> 
  mutate(race = as.factor(race),
         parKat = as.factor(parKat),
         mast_cat1 = as.factor(mast_cat1))
```

```{r}
prd <- predictions(model = scc_high_dp_model,
                   newdata = parit_pred,
                   re.form = NA, type = "response")

scc_parit <- ggplot(prd, aes(x = factor(parKat), y = estimate)) +
  geom_point() +
  geom_segment(aes(x = parKat, y=conf.low, xend = parKat, yend = conf.high))+
  ylim(0.15, 0.6) +
  xlab("parité")+
  ylab("probabilité d'un SCC élevé au dernier contrôle avant tarissement")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

scc_parit
```
```{r}
saveRDS(scc_parit, "generated_datasets/scc_parit.RData")
```

```{r}
race_pred <- race_pred |> 
  mutate(race = as.factor(race),
         parKat = as.factor(parKat),
         mast_cat1 = as.factor(mast_cat1))
```

```{r}
prd <- predictions(model = scc_high_dp_model,
                   newdata = race_pred,
                   re.form = NA, type = "response")

scc_race <- ggplot(prd, aes(x = factor(race), y = estimate)) +
  geom_point() +
  geom_segment(aes(x = race, y=conf.low, xend = race, yend = conf.high))+
  ylim(0.15, 0.6) +
  xlab("race")+
  ylab("probabilité d'un SCC élevé au dernier contrôle avant tarissement")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

scc_race
```

```{r}
saveRDS(scc_race, "generated_datasets/scc_race.RData")
```


```{r}
milk_pred <- milk_pred |> 
  mutate(race = as.factor(race),
         parKat = as.factor(parKat),
         mast_cat1 = as.factor(mast_cat1))
```

```{r}
prd <- predictions(model = scc_high_dp_model, 
                   newdata = milk_pred, 
                   re.form = NA, type = "response")

scc_milk <- ggplot(prd, aes(x = milk_early_max, y = estimate, col = parKat)) +
  geom_line() 

scc_milk
```

```{r}
saveRDS(scc_milk, "generated_datasets/scc_milk.RData")
```


# Probabilité de guérison au tarissement

## modélisation

```{r}
cure_dp_model <- glmer(nxt_cure ~ parKat +
                          milk_early_max_scaled_p1 +
                             milk_early_max_scaled_p2 +
                             milk_early_max_scaled_p3 +
                             milk_early_max_scaled_p4 +
                             mast_cat1 +
                             race + 
                             (1| herd_id),
                           family = binomial(link = "logit"),
                           data = lac, 
                           subset = n_ctrl_early > 0 & repro == 1 & dp_mis == 0 & !is.na(nxt_cure),
                           control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))

summary(cure_dp_model)
```

```{r}
save(cure_dp_model, file = "generated_datasets/cure_dp_model.RData")
```

```{r}
t_cure <- tbl_regression(cure_dp_model, exponentiate = TRUE)
print(t_cure)
```


```{r}
saveRDS(t_cure, "generated_datasets/t_cure.RData")
```


## Prédictions

```{r}
prd1 <- predictions(model = cure_dp_model,
                   newdata = mast_pred,
                   re.form = NA, type = "response")

cure_mam <- ggplot(prd1, aes(x = factor(mast_cat1, level = level_order), y = estimate)) +
  geom_point() +
  geom_segment(aes(x = mast_cat1, y=conf.low, xend = mast_cat1, yend = conf.high))+
  xlab("statut mammite")+
  ylab("probabilité d'une guérison pendant le tarissement")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

cure_mam
```

```{r}
saveRDS(cure_mam, "generated_datasets/cure_mam.RData")
```

```{r}
prd <- predictions(model = cure_dp_model,
                   newdata = parit_pred,
                   re.form = NA, type = "response")

cure_parit <- ggplot(prd, aes(x = factor(parKat), y = estimate)) +
  geom_point() +
  geom_segment(aes(x = parKat, y=conf.low, xend = parKat, yend = conf.high))+
  ylim(0.1, 1)+
  xlab("parité")+
  ylab("probabilité d'une guérison pendant le tarissement")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

cure_parit
```

```{r}
saveRDS(cure_parit, "generated_datasets/cure_parit.RData")
```

```{r}
prd <- predictions(model = cure_dp_model,
                   newdata = race_pred,
                   re.form = NA, type = "response")

cure_race <- ggplot(prd, aes(x = factor(race), y = estimate)) +
  geom_point() +
  geom_segment(aes(x = race, y=conf.low, xend = race, yend = conf.high))+
  ylim(0.1, 1)+
  xlab("race")+
  ylab("probabilité d'une guérison pendant le tarissement")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

cure_race

```

```{r}
saveRDS(cure_race, "generated_datasets/cure_race.RData")
```

```{r}
prd <- predictions(model = cure_dp_model, 
                   newdata = milk_pred, 
                   re.form = NA, type = "response")

cure_milk <- ggplot(prd, aes(x = milk_early_max, y = estimate, col = parKat)) +
  geom_line() 

cure_milk
```


```{r}
saveRDS(cure_milk, "generated_datasets/cure_milk.RData")
```

# Probabilité d'une nouvelle infection après tarissement

## modélisation

```{r}
new_inf_model <- glmer(nxt_ninf ~ parKat +
                          milk_early_max_scaled_p1 +
                             milk_early_max_scaled_p2 +
                             milk_early_max_scaled_p3 +
                             milk_early_max_scaled_p4 +
                             mast_cat1 +
                             race +
                             (1| herd_id),
                           family = binomial(link = "logit"),
                           data = lac, 
                           subset = n_ctrl_early > 0 & repro == 1 & dp_mis == 0 & !is.na(nxt_ninf),
                           control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))

summary(new_inf_model)
```

```{r}
save(new_inf_model, file = "generated_datasets/new_inf_model.RData")
```

```{r}
t_ninf <- tbl_regression(new_inf_model, exponentiate = TRUE)
print(t_ninf)
```

```{r}
saveRDS(t_ninf, "generated_datasets/t_ninf.RData")
```


## Prédictions

```{r}
prd2 <- predictions(model = new_inf_model,
                   newdata = mast_pred,
                   re.form = NA, type = "response")

inf_mam <- ggplot(prd2, aes(x = factor(mast_cat1, level = level_order), y = estimate)) +
  geom_point() +
  geom_segment(aes(x = mast_cat1, y=conf.low, xend = mast_cat1, yend = conf.high))+
  ylim(0.1, 0.5)+
  xlab("statut mammite")+
  ylab("probabilité d'une nouvelle infection pendant le tarissement")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

inf_mam
```
```{r}
saveRDS(inf_mam, "generated_datasets/inf_mam.RData")
```



```{r}
prd <- predictions(model = new_inf_model,
                   newdata = parit_pred,
                   re.form = NA, type = "response")

inf_parit <- ggplot(prd, aes(x = factor(parKat), y = estimate)) +
  geom_point() +
  geom_segment(aes(x = parKat, y=conf.low, xend = parKat, yend = conf.high))+
  ylim(0.1, 0.3)+
  xlab("parité")+
  ylab("probabilité d'une nouvelle infection pendant le tarissement")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

inf_parit
```
```{r}
saveRDS(inf_parit, "generated_datasets/inf_parit.RData")
```

```{r}
prd <- predictions(model = new_inf_model,
                   newdata = race_pred,
                   re.form = NA, type = "response")

inf_race <- ggplot(prd, aes(x = factor(race), y = estimate)) +
  geom_point() +
  geom_segment(aes(x = race, y=conf.low, xend = race, yend = conf.high))+
  ylim(0.1, 0.3)+
  xlab("race")+
  ylab("probabilité d'une nouvelle infection pendant le tarissement")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

inf_race
```
```{r}
saveRDS(inf_race, "generated_datasets/inf_race.RData")
```

```{r}
prd <- predictions(model = new_inf_model, 
                   newdata = milk_pred, 
                   re.form = NA, type = "response")

inf_milk <- ggplot(prd, aes(x = milk_early_max, y = estimate, col = parKat)) +
  geom_line() 

inf_milk
```
```{r}
saveRDS(inf_milk, "generated_datasets/inf_milk.RData")
```

